domain_id = "mixanalog3"
public_host = "localhost"
apps = [
    "mixanalog3",
    "mixanalog3_test",
    "admin"
]

[models.local]
path = "../apis/audiocloud-models/models"

[engines.default]
sample_rate = 192000

[engines.default.resources]
max_concurrent_tasks = 16
ram = 8
cpu = 12.8 # M1: 4 P-cores @ 3.2 GHz

[fixed_instances."distopik:dual1084:0"]
engine_id = "default"
input_start = 0
output_start = 0

[fixed_instances."distopik:summatra:0"]
engine_id = "default"
input_start = 2
output_start = 2
