PUT localhost:7400/v1/apps/mixanalog3/media/01GB9BJ8E9RW24688K11R85BWK/upload
Accept: application/json
Content-Type: application/json

{
  "channels": "stereo",
  "format": "wave",
  "seconds": 51.54,
  "sample_rate": 44100,
  "bytes": 851835,
  "url": "https://www2.cs.uic.edu/~i101/SoundFiles/preamble10.wav",
  "notify_url": "https://en0z7ec5q3k9.x.pipedream.net",
  "context": {
    "test": ["context", "01GB9BJ8E9RW24688K11R85BWK"]
  }
}

###
GET localhost:7400/v1/apps/mixanalog3/media/01GB9BJ8E9RW24688K11R85BWK
Accept: application/json
