[package]
name = "audiocloud-domain-server"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
actix = "0.13"
actix-web = "4.1"
actix-web-actors = "4.1"
actix-cors = "0.6"
actix-broker = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"
serde_json = "1"
anyhow = "1"
once_cell = "1"

[dependencies.sqlx]
version = "0.6"
features = ["sqlite", "runtime-actix-native-tls", "json", "chrono"]

[dependencies.reqwest]
version = "0.11"
features = ["json"]

[dependencies.rdkafka]
version = "0.28"
features = ["gssapi-vendored", "ssl-vendored"]

[dependencies.clap]
version = "3"
features = ["derive", "env"]

[dependencies.audiocloud-api]
path = "../../apis/audiocloud-api"


