on: [ workflow_dispatch ]

name: Build Drivers for Raspberry Pi

jobs:
  build:
    name: Rust build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: domain
        name: Checkout drivers code
      - uses: actions/checkout@v2
        with:
          repository: audiocloud/apis
          path: apis
          ref: main
        name: Checkout API code
      - run: |
          ls -lR
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
        name: Install Rust toolchain for Raspberry Pi
      - uses: ryankurte/action-apt@v0.3.0
        with:
          arch: armhf
          packages: "libssl-dev:armhf"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - uses: actions-rs/cargo@v1
        with:
          args: --release --all-features --target armv7-unknown-linux-gnueabihf -p audiocloud-instance_driver --manifest-path=domain/Cargo.toml --target-dir target
          command: build
          use-cross: true
        name: Build drivers for Raspberry Pi
      - run: |
          ls -lR
        name: List files in target directory
      - uses: actions/upload-artifact@v3
        name: Upload binary artifact
        with:
          name: audiocloud-instance_driver
          path: target/armv7-unknown-linux-gnueabihf/release/audiocloud-instance_driver

